version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html

  # Reste du fichier inchangé
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lamp_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
